---
title: "3_demographics"
author: "Stefan Vermeent"
output:
  word_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(flextable)
library(here)

self_report_clean <- read_csv(here("data", "1_pilot", "self_report_clean.csv"))
```


```{r}
ethnicity <- cleaned_data %>%
  select(id, starts_with("dems")) %>%
  transmute(var = ifelse(dems_ethnicity_mixed == 1, "Mixed", dems_ethnicity)) %>%
  group_by(var) %>%
  summarise(
    percentage = round((n() / nrow(cleaned_data)) * 100, 1),
  ) %>%
  arrange(desc(percentage))

education <- cleaned_data %>%
  select(id, dems_edu) %>%
  transmute(
    var = case_when(
      dems_edu == 1 ~ "Some high school",
      dems_edu == 2 ~ "GED",
      dems_edu == 3 ~ "High school diploma",
      dems_edu == 4 ~ "Some college but no college degree",
      dems_edu == 5 ~ "Associate's degree",
      dems_edu == 6 ~ "Bachelor's or RN degree",
      dems_edu == 7 ~ "Master's degree",
      dems_edu == 8 ~ "Doctoral or law degree"
    )
  ) %>%
  mutate(var = factor(var, levels = c("Some high school", "GED", "High school diploma", "Some college but no college degree", "Associate's degree", "Bachelor's or RN degree", "Master's degree", "Doctoral or law degree"))) %>%
  group_by(var) %>%
  summarise(percentage = round((n() / nrow(cleaned_data)) * 100, 1)) 


gender <- cleaned_data %>%
  select(id, dems_gender) %>% 
  transmute(
    var = case_when(
      dems_gender == 1 ~ "Man",
      dems_gender == 2 ~ "Woman",
      dems_gender == 3 ~ "Non-binary",
      dems_gender == 4 ~ "Other",
      dems_gender == 5 ~ "Prefer not to say"
    )
  ) %>%
  group_by(var) %>%
  summarise(percentage = round((n() / nrow(cleaned_data)) * 100, 1)) %>%
  arrange(desc(percentage))


sex_at_birth <- cleaned_data %>%
  select(id, dems_sex) %>% 
  transmute(
    var = case_when(
      dems_sex == 0 ~ "Male",
      dems_sex == 1 ~ "Female",
      dems_sex == 2 ~ "Intersex",
      dems_sex == 3 ~ "Prefer not to say"
    )
  ) %>%
  group_by(var) %>%
  summarise(percentage = round((n() / nrow(cleaned_data)) * 100, 1)) %>%
  arrange(desc(percentage))

social_class <- cleaned_data %>%
  select(id, dems_class_current) %>% 
  transmute(
    var = case_when(
      dems_class_current == 1 ~ "Poor",
      dems_class_current == 2 ~ "Working class",
      dems_class_current == 3 ~ "Middle class",
      dems_class_current == 4 ~ "Upper-middle class",
      dems_class_current == 5 ~ "Upper class"
    ),
    var = factor(var, levels = c("Poor", "Working class", "Middle class", "Upper-middle class", "Upper class"))
  ) %>%
  group_by(var) %>%
  summarise(percentage = round((n() / nrow(cleaned_data)) * 100, 1))
  
```

# Create table

```{r}
table_demographics <- bind_rows(sex_at_birth, gender, ethnicity, education, social_class) %>%
  mutate(percentage = as.character(percentage)) %>%
  add_row(.before = 1, "var" = "Mean age (SD)", percentage = paste0(round(mean(self_report_clean$dems_age, na.rm=T),2), " (", round(sd(self_report_clean$dems_age, na.rm=T),2), ")")) %>%
  add_row(.before = 2, "var" = "Sex at birth (%)") %>%
  add_row(.before = 6, "var" = "Gender (%)") %>%
  add_row(.before = 12, "var" = "Ethnicity (%)") %>%
  add_row(.before = 22, "var" = "Education level (%)") %>%
  add_row(.before = 31, "var" = "Social class (%)") %>%
  rename(`  ` = var, ` ` = percentage) %>%
  flextable(cwidth = c(3, 1)) %>%
  bold(i = c(1,2,6,12,22,31), j = 1) %>%
  padding(i = c(3:5, 7:11, 13:21, 23:30, 32:36), padding.left = 20) %>%
  align(j = 2, align = "left") %>%
  padding(i = 1, j = 2, padding.left = 20) 

table_demographics
```

```{r}
save(table_demographics, file = here("preregistrations", "1_pilot", "tables", "table_demographics.RData"))
```

