---
bibliography: references.bib
csl: apa.csl
output:
  officedown::rdocx_document:
    page_margins:
      bottom: 1
      footer: 0
      gutter: 0
      header: 0.5
      left: 1
      right: 1
      top: 1
    plots:
      align: center
      caption:
        pre: 'Figure '
        sep: '. '
        style: Image Caption
    reference_docx: reference-doc.docx
    tables:
      caption:
        pre: 'Table '
        sep: '. '
        style: Table Caption
  pdf_document: default
  word_document: default
---

(Note: This document doubles as a preregistration of the pilot study. It was written as a dynamic document with analysis code prior to data collection. For a full history of this document, see the [Open Science Framework (OSF) link](https://osf.io/gfpnr/) to this project). See also the [github link](https://github.com/StefanVermeent/attention_pilot) embedded in the OSF project for a full history of the document)

# Introduction and hypotheses

Childhood adversity outcomes are commonly viewed from a deficit perspective, emphasizing the detrimental effects of adversity on a range of cognitive and behavioral outcomes. Recent years have seen the development of the complimentary hidden talents approach, which stresses that people cognitively adapt to their environment and might therefore develop specific cognitive skills that are ecologically advantageous. However, it remains largely unclear which mechanisms drive specific enhancements and impairments of cognitive abilities. In this pilot study, we test the idea that people who grow up in adversity tend to develop a present-focused attention style, with features that benefit performance on some cognitive tasks but hurt performance on others. 

In line with previous theorizing [e.g., @ellis_2020; @frankenhuis_2016; @frankenhuis_2013], we expect stress-adapted cognitive styles to be characterized by a strong focus on the present.  By cognitive style we mean a collection of relatively stable information processing tendencies (e.g., speed of processing, focus of attention, goal-directed behavior) that together determine how people interact with their environment. We expect that cognitive styles are best understood at the level of more basic cognitive processes. Higher-level processes that are typically targeted in hidden talents studies (e.g., working memory, task-switching) are not fully dissociable processes but instead involve many of the same more basic processes [@conway_2021; @kovacs_2019; @verbruggen_2014]. This overlap means that impairment and enhancement patterns across tasks could be driven by the same underlying process. For example, an attention style that is strongly focused on the here-and-now would be beneficial for basic processing speed and information updating tasks, but might harm performance if in tasks with a lot of distracting stimuli. Thus, common cognitive tasks can be categorized in terms of how they align with certain (aspects of) cognitive styles, and could be experimentally manipulated to increase or decrease their fit to a person’s style.

We focus on two aspects of external attention [i.e., attention pointed at the external environment; @chun_2011] that we expect to develop in harsh and unpredictable environments: 1) A relatively wider scope of attention and 2) an increased sensitivity to subtle changes in the environment. When might these attention styles develop in adverse environments? Attention is involved in information processing on a timescale of seconds to minutes; Focusing attention for longer periods on a single stimulus is impossible for most people [@warm_2008]. Thus, stable attention styles are most useful in response to environmental features that unfold on the same timescale. Factors such as changes in adult household members or frequently moving homes, which are often used as proxies for unpredictability, are unlikely to shape stable attentional styles as they unfold over days or weeks. In addition, any threats that are spatially or temporally predictable (e.g., a specific part of the neighborhood that is known to be dangerous or might be especially dangerous at night) are more likely to lead to signal- or cue-based changes in cognitive processing. Instead, a cognitive style that systematically favors external attention over internal attention should develop when threats are frequent and the environment is chaotic, such that past states of the environment are not predictive of the current state [@emond_2020; @young_2020]. In such an environment, threats might arise at any time and the occasional reward might be fleeting [@ellis_2009; @frankenhuis_2016]. In the absence of reliable cues, a person would benefit from having their attention fixated broadly on the external environment, so that threats and opportunities can be anticipated and dealt with as soon as they appear. 


The current pilot study had two primary aims: First, we tested whether people from harsh and unpredictable environments would perform better on attention tasks that favor a broad attention scope and a sensitivity to subtle changes. To this end, participants completed three attention tasks that differed in the extent to which they would favor or punish these attention features. Second, we investigated the link between adversity and attention both in a traditional analysis of reaction times, as well as by using the Drift Diffusion Model [DDM; @forstmann_2016; @ratcliff_2015; @ratcliff_2008] to more precisely disentangle the underlying cognitive processes (for more details on the DDM analysis, see the [analyses](#analyses) section).

Our primary hypotheses were as follows:

1) People with more exposure to violence and environmental unpredictability during childhood will show enhanced or equal performance compared to people from safe environments on tasks that require quickly detecting peripheral stimuli and detecting subtle changes (i.e., the Cued Attention Task and Change Detection Task). This effect is at least partly explained by an increased drift rate in the DDM analysis

2) People with more exposure to violence and environmental unpredictability during childhood will perform worse on tasks that require ignoring distracting peripheral stimuli (i.e., the Flanker Task). This effect is at least partly explained by a wider initial attentional focus, as quantified by an SDDM analysis.

In addition, the pilot study had a number secondary aims: First, we investigated whether the link between measures of adversity and attention would be contingent on the timescale of the adversity items. More specifically, we explored whether stable attention styles might be better predicted by items of momentary unpredictability (e.g., "things were often chaotic in my house") than by items of temporally extended unpredictability ("At least one of my parents changed jobs frequently"). Second, we conducted exploratory correlation analyses between measures of adversity, attention, and measures of temporal orientation (i.e., impulsivity and future orientation). Third, we explored whether potential effects of adversity on task performance might be moderated by current states of anxiety, hunger, or sleep deprivation. Fourth, we explored the extent to which our retrospective measures of adversity correlate with current depressive symptoms, which could be a potential confound [@nivison_2021].

# Methods {#methods}

## Participants {#participants}

Participants were XXX US-based individuals between the ages of 18 and 30 (*M* = `r #TBD`, *SD* = `r #TBD`). We decided for this age cut-off to limit the effect of healthy age-related cognitive decline on speeded cognitive tasks, which becomes more pronounced after age 30 [@salthouse_2010]. Recruitment took place through Prolific. Participants were eligible for for the study if they were between 18 and 30 years old, if English was their primary language, if they were currently residing in the United States, if they did not have a history of brain injury, if they did not have color blindness, and if they had normal or corrected-to-normal eyesight.

The sample size was determined by a [preregistered power analysis](https://osf.io/gfpnr/))).
[...]


## Exclusion criteria {#exclusion}

We applied several exclusion criteria prior to inspecting or testing any of the relationships between independent and dependent variables. First, we excluded participants with incomplete data on any of the attention tasks (*N* = `r #TBD `). Second, we excluded participants who did not have normal or corrected-to-normal vision (*N* = `r #TBD `). Third, we analyzed responses to the attention checks and reversed coded items in the questionnaire part of the experiment. We excluded participants if they missed both attention check items or if they had suspicious response patterns (e.g., consistently endorsing high response options even when some items were reversed coded) (*N* = `r #TBD `). 

In addition, we screened the reaction times on each of the three attention tasks. For the Drift Diffusion analyses, it is important that each response is generated by a diffusion process (as opposed to, for example, guessing). To this end, trials with reaction times < 250ms or longer than 3500ms [@ratcliff_2015] were excluded from the analyses (*N* = `r #TBD `). Participants for whom more than 10 trials were removed were excluded from the analyses (N = `r #TBD `).  

## Procedure {#procedure}

The experiment was completed on the participants' own laptop or desktop computer and consisted of three parts: written consent, attention task battery, questionnaire battery, brief demographics form, and final checks and the opportunity to give feedback on the experiment. The demographics questions asked about the participant's age, sex at birth, gender, ethnicity, social class, education level, occupation, and household income. In addition, we checked whether participants had color blindness and whether they had normal or corrected-to-normal vision. At the end of the experiment, participants were asked whether they ever got up and left during the study and whether they were ever interrupted during the study (answers on these questions did not affect compensation).

After providing written consent, participants started with the three attention tasks. They were asked to complete the attention tasks in a quiet room in the house where they would be least likely to be distracted by other people or outside noises. The order of the tasks was counterbalanced between subjects. At the onset of the first task, the experiment went into full-screen mode to limit distractions from other programs or browser tabs. The size of the task stimuli was controlled between subjects using the resize plugin in JsPsych. Participants were asked to hold a creditcard (or similarly sized card) up against the screen and to increase the size of a blue rectangle on the screen until it matched the size of the creditcard. The stimulus display for each task was resized so that 100 pixels corresponded to 1 inch for all participants. After succesfully resizing the screen, participants completed all three tasks. Whenever participants had to respond by use of their keyboard, the cursor was hidden from the screen to minimize distractions.


## Measures {#measures}

The attention tasks were programmed in JsPsych version 3.6.1 [@deLeeuw_2015]. 

### Cued attention task {#cued_attention}

The cued attention task is an adaptation of the Posner task [@posner_1980]. On each trial, a left- or right-pointing arrow is presented in one of eight random locations at a distance of 300 pixels from the center of the screen (see Figure 1B). Participants have to indicate the direction of the arrow by pressing either the left- or right arrow key on their keyboard. On 50% of the trials, the arrow is preceded by a cue ("\*") in the exact same location (i.e., cued trials). On the other 50% of the trials, the cue ("\*") is presented at the center of the screen (i.e., neutral trials). Thus, on the cued trials, the location of the cue deterministically predicts the location of the arrow, whereas on the neutral trials the arrow will always appear in a different location.

Each trial starts with a fixation cross presented at the center of the screen for 1000ms. Then, the cue is presented for 250ms either at the center of the screen or in the location where the arrow will appear. Finally, the arrow is presented until a response is given by the participant. The cued attention task begins with eight practice trials (four cued and four neutral trials) in which participants receive performance feedback after each trial (either "Correct!" printed in green or "Incorrect!" printed in red). After finishing the practice round, participants complete a single test block consisting of a total of 64 trials (two repetitions of all parameter combinations: arrow location (top center vs. top left vs. center left vs. bottom left vs. bottom center vs. bottom right vs. center right vs. top right) X arrow direction (left vs. right) X condition (cued vs. neutral)).


### Flanker task {#flanker}

On each trial of the Flanker task [@eriksen_1974], participants are presented with a set of five arrows pointing either left or right. Their job is to indicate the direction of the central arrow while ignoring the flanking arrows to the left and right (see Figure 1A). On 50% of the trials, the flanking arrows point in the same direction as the central arrow (i.e., congruent trials), and on the other 50% of the trials they point in the opposite direction (i.e., incongruent trials). The arrows are randomly presented in the top-half or bottom-half of the screen. This is done to prevent participants from being able to fixate on the center of the screen, which would reduce the interfering effect of the flanking arrows.

Each trial starts with a fixation cross presented at the center of the screen. After a variable delay (randomly sampled from a uniform distribution from 800ms to 1200 ms with time steps of 50ms), the arrows are presented either in the top- or bottom-half of the screen. Participants have 2000ms to indicate the direction of the center arrow. The Flanker task begins with eight practice trials in which participants receive performance feedback after each trial (either "Correct!" printed in green or "Incorrect!" printed in red). After finishing the practice round, participants complete a single test block consisting of a total of 64 trials (eight repetitions of all parameter combinations: arrow location (top vs. bottom) X central arrow direction (left vs. right) X condition: (congruent vs. incongruent)). Participants do not receive performance feedback during the test block.

### Change detection task {#change}

On each trial of the change detection task, participants are presented with five colored circles against a grey background, each with a radius of 15 pixels (see Figure 1C). Each circle is located in a random location within a pre-specified area of 50 by 50 pixels to prevent overlap. Participants have 1000ms to memorize the locations of the five circles around the fixation cross. After 1000ms, the circles briefly disappear for 500ms and then reappear again. On 50% of the trials, one of the circles has moved to another location for a fixed total of 40 pixels in a 360 degree direction. On the other 50% of the trials, all circles are still in the same location as the initial memory display. Participants have to indicate whether they think one of the circles changed location (by pressing the left-arrow key) or whether they think all circles are still in the same location (by pressing the right-arrow key). Note that the only potential difference between the memory and probe display is the displacement of **one** circle; the remaining circles are always in the same place and circles never change color within a trial.

The change detection task starts with five practice trials in which participants receive performance feedback after each trial (either "Correct!" printed in green or "Incorrect!" printed in red). After finishing the practice round, participants complete two test blocks consisting of 25 trials each (50 trials in total). The design is fully counterbalanced so that on each "movement" trial, each of the five circles changes five times per block for each of the five colors. Participants do not receive performance feedback during the two test blocks.

### State anxiety {#state}

We assessed state anxiety during the experiment using the state subscale of the State-Trait Anxiety Inventory [STAI-S; @spielberger_1999]. The STAI-S contains 20 short items measuring current anxiety rated on a scale of 1 (not al all) to 4 (very much so): 1) "I feel calm" (reversed); 2) "I feel secure" (reversed); 3) "I feel tense"; 4) "I feel strained"; 5) "I feel at ease" (reversed); 6) "I feel upset"; 7) "I am presently worrying over possible misfortunes"; 8) "I feel satisfied" (reversed); 9) "I feel frightened"; 10) "I feel comfortable" (reversed); 11) "I feel self-confident" (reversed); 12) "I feel nervous"; 13) "I am jittery"; 14) "I feel indecisive"; 15) "I am relaxed" (reversed); 16) "I feel content" (reversed); 17) "I am worried"; 18) "I feel confused"; 19) "I feel steady" (reversed); 20) "I feel pleasant" (reversed).

An overall state anxiety variable was computed by averaging the 20 items (*M* = `r #TBD `, *SD* = `r #TBD `, $\alpha$ = `r #TBD `).

### Violence exposure {#violence}

Violence exposure was measured using the Neighborhood Violence Scale [NVS; Frankenhuis & Bijlstra, 2018; Frankenhuis, de Vries, Bianchi, & Ellis, 2020] and two items assessing exposure to physical fights before age 13. The NVS contains seven items rated on a scale from 1 (never true) to 5 (very often true): 1) "I grew up in a safe neighborhood"; 2) "Crime was common in the neighborhood where I grew up"; 3) "In the neighborhood where I grew up, people had plenty of money" (reversed); 4) "In the neighborhood where I grew up, physical fights were common"; 5) "In the neighborhood where I grew up, shootings or stabbings occurred"; 6) "In the neighborhood where I grew up, most people felt unsafe walking alone after dark"; 7) "Where I grew up, it was important to be able to defend yourself against physical harm". The physical fighting items assessed witnessing fights: "Based on your experiences, how many times did you see or hear someone being beaten up in real life, before age 13?" and "How many times were you in a physical fight, before age 13?" Answers to both items ranged from 1 (0 times) to 8 (12 or more times).

An overall violence exposure variable was computed by separately standardizing the NVS (*M* = `r #TBD `, *SD* = = `r #TBD `, $\alpha$ = `r #TBD `) and physical fighting items and averaging them together (*r* = `r #TBD `).

### Unpredictability {#unpred}

Unpredictability before age 13 was measured using two different scales: A scale of perceived childhood unpredictability used in previous research [@mittal_2015; @young_2018] and the Questionnaire of Unpredictability in Childhood [QUIC; @glynn_2019]. The scale of perceived childhood unpredictability contains eight items rated on a scale of 1 (never true) to 5 (very often true): 1) "My family life was generally inconsistent and unpredictable from day-to-day"; 2) "My parent(s) frequently had arguments or fights with each other or other people in my childhood", 3) My parents had a difficult divorce or separation during this time"; 4) "People often moved in and out of my house on a pretty random basis"; 5) "When I woke up, I often didn't know what could happen in my house that day"; 6) "My family environment was often tense and "on edge""; 7) Things were often chaotic in my house"; 8) "I had a hard time knowing what my parent(s) or other people in my house were going to say".

We included the QUIC because it captures several dimensions of environmental and household unpredictability with a better (but not perfect) distinction between items capturing more short-term unpredictability (i.e., on the level of seconds to minutes) and more long-term unpredictability (i.e., on the level of days to months (or longer)). Note that the scale of perceived childhood unpredictability combines items on a short-term scale (e.g., item 1) with items measured on a long-term scale (e.g., item 3) which might have different effects on the development of specific attention styles. the QUIC consists of 38 items across five subscales. Parental monitoring and involvement: 1) "I had a set morning routine on school days (i.e., I usually did the same thing each day to get ready)"; 2) "My parents kept track of what I ate (e.g., made sure that I didn’t skip meals or tried to make sure I ate healthy food)" (reversed); 3) "My family ate a meal together most days" (reversed); 4) "My parents tried to make sure I got a good night’s sleep (e.g., I had a regular bedtime, my parents checked to make sure I went to sleep)" (reversed); 5) "I had a bedtime routine (e.g, my parents tucked me in, my parents read me a book, I took a bath)" (reversed); 6) "In my afterschool or free time hours at least one of my parents knew what I was doing" (reversed); 7) "At least one of my parents regularly checked that I did my homework" (reversed); 8) "At least one of my parents regularly kept track of my school progress" (reversed); 9) "At least one parent made time each day to see how I was doing". Parental predictability: 1) "My parents were often very late to pick me up (e.g., from school, aftercare or sports)"; 2) "I usually knew when my parents were going to be home" (reversed); 3) "At least one of my parents had punishments that were unpredictable"; 4) "I often wondered whether or not one of my parents would come home at the end of the day"; 5) "My family planned activities to do together" (reversed); 6) "At least one of my parents would plan something for the family, but then not follow through with the plan"; 7) "My family had holiday traditions that we did every year (e.g., cooking a special food at a particular time of year/decorate the house the same way)" (reversed). 8) "At least one of my parents was disorganized"; 9) "At least one of my parents was unpredictable"; 10) "For at least one of my parents, when they were upset I did not know how they would act"; 11) "One of my parents could go from calm to furious in an instant"; 12) "One of my parents could go from calm to stressed or nervous in an instant". Parental environment: 1) "There was a long period of time when I didn’t see one of my parents (e.g., military deployment, jail time, custody arrangements)"; 2) "I experienced changes in my custody arrangement"; 3) "At least one of my parents changed jobs frequently"; 4) "There were times when one of my parents was unemployed and couldn’t find a job even though he/she wanted one"; 5) "My parents had a stable relationship with each other" (reversed); 6) "My parents got divorced"; 7) "At least one of my parents had many romantic partners". Physical environment: 1) "There were often people coming and going in my house that I did not expect to be there"; 2) "I moved frequently"; 3) "I changed schools frequently"; 4) "I changed schools mid-year"; 5) "I lived in a clean house" (reversed); 6) I lived in a cluttered house (e.g., piles of stuff everywhere); 7) "In my house things I needed were often misplaced so that I could not find them". Safety and security: 1) "There was a period of time when I often worried that I was not going to have enough food to eat."; 2) "There was a period of time when I often worried that my family would not have enough money to pay for necessities like clothing or bills"; 3) "There was a period of time when I did not feel safe in my home". All items were endorsed as either "yes" or "no".

We computed several unpredictability variables to be able to assess how they would relate to the dependent variables as well as to each other: 1) overall perceived unpredictability variable containing all eight items of the perceived unpredictability scale (*M* = `r #TBD `, *SD* = = `r #TBD `, $\alpha$ = `r #TBD `); 2) an overal QUIC variable as the sum of all 38 items (*M* = `r #TBD `, *SD* = = `r #TBD `, $\alpha$ = `r #TBD `); 3) five separate QUIC subscales as the sum of their sub-items (*M* = `r #TBD `, *SD* = = `r #TBD `, $\alpha$ = `r #TBD `).

### Household chaos {#chaos}

We assessed household chaos before age 13 using the Confusion, Hubbub, and Order Scale [CHAOS; @matheny_1995]. The CHAOS consists of 15 items rated on a scale of 1 (Never true) to 5 (Very often true). (Note that the original scale consists of binary "true" or "false" response options). The items were: 1) "There was very little commotion in our home", 2) "We could usually find things when we needed them"; 3) "We almost always seemed to be rushed"; 4) "We were usually able to stay on top of things"; 5) "No matter how hard we tried, we always seemed to be running late"; 6) "It was a real zoo in our home"; 7) "At home we could talk to each other without being interrupted"; 8) "There was often a fuss going on at our home"; 9) "No matter what our family planned, it usually didn't seem to work out"; 10) "You couldn't hear yourself think in our home"; 11) "I often got drawn into other people's arguments at home"; 12) "Our home was a good place to relax"; 13) "The telephone took up a lot of our time at home"; 14) "The atmosphere in our home was calm"; 15) "First thing in the day, we had a regular routine at home". 

An overall household chaos variable was computed by averaging the 15 items (*M* = `r #TBD `, *SD* = `r #TBD `, $\alpha$ = `r #TBD `).

### Impulsivity {#impulsivity}

We assessed general impulsivity with the Motor Impulsivity subscale of the [Barrett Impulsivity Scale (BIS); @patton_1995; @spinella_2007]. The Motor Impulsivity subscale of the BIS consists of five items rated on a scale of 1 (never true) to 5 (very often true): 1) "I do things without thinking"; 2) "I say things without thinking"; 3) "I act on the spur of the moment"; 4) "I buy things on impulse"; 5) "I act on impulse".

An overall motor impulsivity variable was computed by averaging the 5 items (*M* = `r #TBD `, *SD* = `r #TBD `, $\alpha$ = `r #TBD `). 

### Future Orientation {#future_orientation}

We assessed future orientation with an adapted version of the Future Orientation Scale [FOS; @steinberg_2009]. The original scale consists of 15 sets of opposing items separated by "BUT" (e.g., "Some people like to plan things out one step at a time BUT other people like to jump right into things without planning them out beforehand"). Participants first choose the item that best matches their general preference, and then indicate whether the statement is "really true" or "somewhat true". We adapted this format to a single statement per item (by picking each statement in the original right-hand column) presented in a first-person format in an attempt to reduce the cognitive load of the items. We were worried that people with less formal education or who were sitting in a noisier environment would struggle with the original items. The 15 adapted items were rated on a scale of 1 (never true) to 5 (very often true): 1) "I jump right into things without planning them beforehand"; 2) "I spend a lot of time thinking about how things might be in the future" (reversed); 3) "I don't think about every little possibility before making a decision"; 4) "When I act, I don't think about the consequences"; 5) "I give up my happiness now to get what I want in the future" (reversed); 6) "Making lists of things to do is a waste of time"; 7) "I usually make plans before going ahead with my decision" (reversed); 8) "I'd rather spend money right away than save it for a rainy day"; 9) "I am pretty good at seeing in advance how one thing can lead to another" (reversed); 10) "I think a lot about how my decisions will affect others" (reversed); 11) "I don't try to imagine what my life will be like in 10 years"; 12) "Things work out better if they are planned out in advance" (reversed); 13) "Breaking big projects down into small steps isn't really necessary"; 14) "I am always thinking about what tomorrow will bring" (reversed); 15) "It is best not to worry about things you can't predict".

An overall future orientation variable was computed by averaging the 15 items (*M* = `r #TBD `, *SD* = `r #TBD `, $\alpha$ = `r #TBD `). In addition, we calculated subscales for "Planning ahead" (items 1, 6, 7, 12 and 13), "Time Perspective" (items 2, 5, 8, 11 and 14) and "Anticipation of Future Consequences" (items 3, 4, 9, 10 and 15).

### Depressive symptoms {#depression}

We assessed depressive symptoms during the past week using the Center for Epidemiologic Studies Depression Scale [CESD; @radloff_1977]. The scale consists of 20 items rated from 1 (rarely or none of the time (less than 1 day)) to 4 (most or all of the time (5-7 days)): 1) "I was bothered by things that usually don't bother me"; 2) "I did not feel like eating; my appetite was poor"; 3) "I felt that I could not shake off the blues even with help from my family and friends"; 4) "I felt that I was just as good as other people" (reversed); 5) "I had trouble keeping my mind on what I was doing"; 6) "I felt depressed"; 7) "I felt that everything I did was an effort"; 8) "I felt hopeful about the future" (reversed); 9) "I thought my life had been a failure"; 10) "I felt fearful"; 11) "My sleep was restless"; 12) I was happy" (reversed); 13) "I talked less than usual"; 14) "I felt lonely"; 15) "People were unfriendly"; 16) "I enjoyed life" (reversed); 17) "I had crying spells"; 18) "I felt sad"; 19) "I felt that people dislike me"; 20) "I could not get 'going'".

## Data analyses

### Reaction Times

For the Cued Attention Task and Flanker Task, average reaction times per participant were calculated separately for each condition (cued/neutral trials and incongruent/congruent trials, respectively). For the change detection task, we calculated an average reaction time across all trials. If necessary for meeting model assumptions, reaction times were log-transformed. We did not plan on conducting analyses on the proportion of errors as error rates are generally very low on similar Cued Attention and Flanker tasks (i.e., < 5% of trials). Note that the DDM analysis provides a full breakdown of performance both in terms of reaction times and accuracy.

For the Cued Attention Task and Flanker Task, we performed a set of linear mixed effects analyses to test adversity X condition interactions on mean RTs. All models included a random intercept for participants. Across separate models, adversity was operationalized as childhood violence exposure and childhood unpredictability. For violence exposure, we used aggregated violence exposure variable. For unpredictability, we used the 



The effect of different dimensions of adversity on mean RTs was assessed both using linear mixed effects models (for the Cued Attention Task and the Flanker Task) and linear regressions (Change Detection Task). 

For the Cued Attention Task and the Flanker Task, we performed a set of linear mixed effects analyses separately for different measures of adversity and task condition (cued vs. neutral) as well their interaction. For 


The models included a random intercept for participants. The adversity measures included as independent variables were 


### Drift Diffusion Model

The Drift Diffusion Model (DDM; @ratcliff_2008; @ratcliff_2015) is a cognitive model that accounts for the fundamental cognitive processes underlying two-alternative forced-choice paradigms (2-AFC; see Figure XXX). The model assumes that the decision-making process constitutes a noisy information accumulation process that continues until one of two decision boundaries (corresponding to one of two response options) is reached. As soon as the accumulation process reaches a decision boundary, the process terminates and a motor response is initiated. The DDM computes four parameters that map onto distinct cognitive processes [@voss_2004]. The accumulation process is modeled as a drift rate (*v*), reflecting basic cognitive speed. large values of *v* reflect more efficient processing (faster and more accurate). Unless people are biased to favor one response over the other (e.g., due to a skewed reward structure), the starting point (*z*) of the accumulation process is usually fixed to be equidistant from both decision boundaries (*a*). larger values of *a* reflect more conservative responses (slower but more accurate) while smaller values of *a* reflect more liberal responses (faster but less accurate). The fourth and final parameter is the non-decision time (*Ter*), which includes a collection of processes that are not related to the decision process (e.g., initial stimulus encoding and initiating the motor response). Importantly, the DDM parameters account for the full pattern of correct RTs, incorrect RTs, and proportion of errors.

The DDM is fit separately to the data of each participant. For the data of the Change Detection Task and the Cued Attention Task, the DDM was fit using Fast-dm [@voss_2007]. We used Maximum Likelihood estimation as it has been shown to provide reliable estimates with relatively few trials [@lerche_2017; see also our power simulations on [OSF](https://osf.io/gfpnr/)]. *a*, *v* and *Ter* were freely estimated and *z* was fixed to 0.5 (the midpoint). In addition, all inter-trial variability parameters were fixed to 0 to increase model parsimony. For the Cued Attention Task, the DDM was fit separately to data of the cued and neutral condition. For the Change Detection task, the DDM was fit to all trials.

The DDM analysis of the Flanker task was done using an adaptation of the standard DDM that was specifically developed to account for Flanker data: The Spotlight Drift Diffusion Model [SDDM; @grange_2016; @white_2018a; @white_2018b, @white_2011]. The standard DDM model assumes a stable drift rate over time within trials (i.e., the rate of information accumulation does not change over time). However, on the Flanker Task, reaction time patterns indicate that the drift rate increases over time, thus violating the basic assumption of the standard DDM [@white_2011]. The SDDM explains this pattern by assuming that attention on the Flanker task works like a spotlight that starts relatively broad, and then gradually narrows down to the central arrow over time. Each arrow provides perceptual input *p*. If the flanking arrows are congruent, all flankers take a positive value for *p*; if the flanking arrows are incongruent, they take a negative value for *p* while the central arrow takes a positive value. The drift rate (*v*) at each time point is the function of the strength of perceptual input *p* multiplied by the amount of attention focused on each arrow. Attention is operationalized by two additional parameters: the initial width of the attentional spotlight (*SD~a~*) and the shrinking rate of the attentional spotlight (*rd*). The attentional spotlight is assumed to be normally distributed over the arrows, with relatively more attention paid to the arrows at the center and relatively less attention paid to the peripheral arrows. Over time, this normal distribution (*SD~a~*) narrows down to the central arrow at the rate specified by *rd*, thereby gradually decreasing the interfering effect of the flanking arrows. Note that the SDDM is based on a combined analysis of congruent and incongruent trials. See Figure 1B for a visualization of the SDDM.

Previous research has shown that it is not useful to interpret both *SD~a~* and *rd* since they trade-off against each other [i.e., a wide initial spotlight combined with a large shrinking rate leads to similar patterns as a narrow initial spotlight combined with a low shrinking rate; @white_2018a; @white_2011]. Most previous studies have fixed *SD~a~* and only estimated *rd*, or calculated a *SD~a~*/*rd* ratio, which serves as a measure of interference. However, our primary interest lies in the initial width of the attentional spotlight, which we hypothesize to be wider for people from harsh and unpredictable environments compared to people from safe and predictable environments. In this pilot study, we fitted several SDDM models either estimating both attention parameters or fixing *rd* to see how it affected model fit (more details below). Model fit was done using the `flankr` package in R [@grange_2016].

### Effect of adversity on task performance

The effect of different dimensions of adversity on attention task performance was assessed both using linear mixed effects models (for the Cued Attention Task) and linear regressions (for the Flanker Task and the Change Detection Task). Dependent variables were mean RTs and DDM parameters. While our hypotheses were specific to DDM parameters *v* (for the Flanker Task and the Change Detection Task) and *SD~a~*, we repeated the analyses using DDM parameters *a* and *Ter* (but not *z*), and SDDM parameters *a*, *p*, *Ter* and *SD~a~*/*rd* (but not *rd*).

For the Cued Attention Task, we performed a set of linear mixed effects analyses separately for different measures of adversity and task condition (cued vs. neutral) as well their interaction. For 


The models included a random intercept for participants. The adversity measures included as independent variables were 

### Secondary analyses

We computed Pearson correlations between all adversity measures, temporal orientation measures, state measures, and attention tasks..

