primary_pooled_ssp_decisions <- tribble(
  ~spec_var,               ~spec_expr,                                                      ~name,
  "dv_type",              "a_flanker",                                                     "Boundary separation (a)",
  "dv_type",              "t0_flanker",                                                    "Non-decision time (t0)",
  "dv_type",              "p_flanker",                                                     "Perceptual input (p)",
  "dv_type",              "sda_flanker",                                                   "Initial width (sda)",
  "dv_type",              "rd_flanker",                                                    "Shrinking rate (rd)",
  "dv_type",              "interference_flanker",                                          "sda / rd (interference)",
  "no_resize",            "scale_factor %in% c(0,1)",                                      "Include all scalers",
  "no_resize",            "scale_factor == 1",                                             "Exclude all scalers",
  "no_resize",            "study == -1 | (study == 1 & scale_factor == '1')",              "Exclude non-scalers study 1",
  "no_resize",            "study == 1 | (study == -1 & scale_factor == '1')",              "Exclude non-scalers pilot",
  "no_fullscreen",        "fullscreenenter %in% c(0,1)",                                   "Include no fullscr. enter",
  "no_fullscreen",        "fullscreenenter == 1",                                          "Exclude no fullscr. enter",
  "exit_fullscreen",      "fullscreenexit %in% c(0,1)",                                    "Include fullscr. exit",
  "exit_fullscreen",      "fullscreenexit == 0",                                           "Exclude fullscr. exit",
  "interrupted",          "attention_interrupt_sum %in% c(0,1,2)",                         "All interruptions",
  "interrupted",          "attention_interrupt_sum < 1",                                   "No extreme interruptions",
  "noise",                "att_noise %in% c(0,1,2,3,4)",                                   "All noise levels",
  "noise",                "att_noise %in% c(0,1,2)",                                       "No high noise levels",
  "outliers",             "{dv_type}_z < 10",                                              "Include all scores",
  "outliers",             "{dv_type}_z < 3.2",                                             "Exclude scores > 3.2SD",
)


primary_condition_ssp_decisions <- tribble(
  ~spec_var,               ~spec_expr,                                                      ~name,
  "dv_type",              "a_flanker",                                                     "Boundary separation (a)",
  "dv_type",              "t0_flanker",                                                    "Non-decision time (t0)",
  "dv_type",              "p_flanker",                                                     "Perceptual input (p)",
  "dv_type",              "sda_flanker",                                                   "Initial width (sda)",
  "dv_type",              "rd_flanker",                                                    "Shrinking rate (rd)",
  "dv_type",              "interference_flanker",                                          "sda / rd (interference)",
  "no_resize",            "scale_factor %in% c(0,1)",                                      "Include all scalers",
  "no_resize",            "scale_factor == 1",                                             "Exclude all scalers",
  "no_fullscreen",        "fullscreenenter %in% c(0,1)",                                   "Include no fullscr. enter",
  "no_fullscreen",        "fullscreenenter == 1",                                          "Exclude no fullscr. enter",
  "exit_fullscreen",      "fullscreenexit %in% c(0,1)",                                    "Include fullscr. exit",
  "exit_fullscreen",      "fullscreenexit == 0",                                           "Exclude fullscr. exit",
  "interrupted",          "attention_interrupt_sum %in% c(0,1,2)",                         "All interruptions",
  "interrupted",          "attention_interrupt_sum < 1",                                   "No extreme interruptions",
  "noise",                "att_noise %in% c(0,1,2,3,4)",                                   "All noise levels",
  "noise",                "att_noise %in% c(0,1,2)",                                       "No high noise levels",
  "outliers",             "{dv_type}_z < 10",                                              "Include all scores",
  "outliers",             "{dv_type}_z < 3.2",                                             "Exclude scores > 3.2SD",
)


secondary_condition_unp_expl_decisions <- tribble(
  ~spec_var,               ~spec_expr,                                                      ~name,
  "dv_type",              "a_flanker",                                                     "Boundary separation (a)",
  "dv_type",              "t0_flanker",                                                    "Non-decision time (t0)",
  "dv_type",              "p_flanker",                                                     "Perceptual input (p)",
  "dv_type",              "sda_flanker",                                                   "Initial width (sda)",
  "dv_type",              "rd_flanker",                                                    "Shrinking rate (rd)",
  "dv_type",              "interference_flanker",                                          "sda / rd (interference)",
  
  
  "iv_type",              "unp_pcunp_quic_comp_c",                                         "PCU + QUIC",
  "iv_type",              "chaos_mean_c",                                                  "CHAOS",
  "iv_type",              "unp_subj_comp_c",                                               "Subjective",
  "iv_type",              "unp_obj_comp_c",                                                "Objective",
  "iv_type",              "quic_monitoring_mean_c",                                        "QUIC - Monitoring",
  "iv_type",              "quic_par_predict_mean_c",                                       "QUIC - Par. Predict.",
  "iv_type",              "quic_par_env_mean_c",                                           "QUIC - Par. Env.",
  "iv_type",              "quic_phys_env_mean_c",                                          "QUIC - Phys. Env.",
  "iv_type",              "quic_safety_mean_c",                                            "QUIC - Safety & Security",
  
  "no_resize",            "scale_factor %in% c(0,1)",                                      "Include all scalers",
  "no_resize",            "scale_factor == 1",                                             "Exclude all scalers",
  "no_fullscreen",        "fullscreenenter %in% c(0,1)",                                   "Include no fullscr. enter",
  "no_fullscreen",        "fullscreenenter == 1",                                          "Exclude no fullscr. enter",
  "exit_fullscreen",      "fullscreenexit %in% c(0,1)",                                    "Include fullscr. exit",
  "exit_fullscreen",      "fullscreenexit == 0",                                           "Exclude fullscr. exit",
  "interrupted",          "attention_interrupt_sum %in% c(0,1,2)",                         "All interruptions",
  "interrupted",          "attention_interrupt_sum < 1",                                   "No extreme interruptions",
  "noise",                "att_noise %in% c(0,1,2,3,4)",                                   "All noise levels",
  "noise",                "att_noise %in% c(0,1,2)",                                       "No high noise levels",
  "outliers",             "{dv_type}_z < 10",                                              "Include all scores",
  "outliers",             "{dv_type}_z < 3.2",                                             "Exclude scores > 3.2SD",
)
