---
title: "R Notebook"
output: html_notebook
---


```{r}
library(reticulate)

use_condaenv("py37")
hddm <- reticulate::import("hddm")
reticulate::import("pandas", as = "pd")
reticulate::import("matplotlib.pyplot", as = "plt")
```


```{r}
# 2. Load data ---------------------------------------------
hddm_data <- flanker_data_clean_average %>%
  select(flanker_data_long) %>%
  mutate(
    flanker_data_long = map(flanker_data_long, function(x) {
      
      
      x %>%
        mutate(rt=rt/1000) %>%
        select(-response) %>%
        rename(subj_idx = id, response = correct) %>%
        select(subj_idx, condition, congruency, response, rt)
    }) 
  ) %>%
  unnest(flanker_data_long)

hddm_data_std <- hddm_data %>% filter(condition == "standard", subj_idx %in% 1:10)
hddm_data_enh <- hddm_data %>% filter(condition == "enhanced")
hddm_data_deg <- hddm_data %>% filter(condition == "degraded")
```

```{r}
# 3. HDDM --------------------------------------------------------------------

## 3.1 Models ----

  # a. Parameters fixed (i.e., equal) across congruency levels; standard condition
  # b. Parameters freely estimated across congruency levels; standard condition


## 3.2 Standard condition: Model a ---- 

### 3.2.1 Initiate and fit model
py_run_string("mod_fixed_std = r.hddm.HDDM(data = r.hddm_data_std, bias = False)")            
py_run_string("mod_fixed_std.find_starting_values()")                                 
py_run_string("hddm_fixed_std = mod_fixed_std.sample(500, burn=10)")    

```


```{python}
mod_fixed_std = r.hddm.HDDM(data = r.hddm_data_std, bias = False)           
mod_fixed_std.find_starting_values()                                
hddm_fixed_std = mod_fixed_std.sample(500, burn=10)
```

